#!/usr/bin/env node
/* RATTLE — inject `par` (verifier bot-optimal tap count) into every level in
   web/js/levels.js, for the efficiency-star system (3★ = used ≤ par+1). Reuses the
   existing certified level objects (no reseed) + re-serialises. gen-campaign.cjs
   also emits par on future regens; this back-fills the current file. */
const path = require("path"), fs = require("fs");
const G = require(path.join(__dirname, "..", "..", "web", "js", "engine.js"));
const { LEVELS } = require(path.join(__dirname, "..", "..", "web", "js", "levels.js"));
function rem(w){let r=0;for(const o of w.objectives){if(o.kind==="pop"||o.kind==="shells"||o.kind==="balloons")r+=o.rem;else if(o.kind==="duck"&&!w.duckDone)r+=8;}return r;}
function beam(spec,W,D){const w=G.createWorld(spec);let fr=[{s:G.snapshot(w)}];const seen=new Set();for(let d=1;d<=D;d++){const kids=[];for(const nd of fr){G.restore(w,nd.s);const mv=G.poppableClusters(w).map(i=>({t:"p",i}));mv.push({t:"r"});for(const m of mv){G.restore(w,nd.s);if(m.t==="r"){if(w.taps<=0)continue;w.taps--;w.tapCounter++;G.applyRattle(w);}else{w.taps--;w.tapCounter++;G.popClusterIdx(w,m.i);}G.settle(w);if(G.isWin(w))return d;if(G.isLose(w)||w.taps<=0)continue;const k=rem(w)+":"+w.balls.reduce((n,b)=>n+(b.alive?1:0),0)+":"+w.taps;kids.push({s:G.snapshot(w),sc:rem(w),k});}}kids.sort((a,b)=>a.sc-b.sc);fr=[];for(const k of kids){if(seen.has(k.k))continue;seen.add(k.k);fr.push(k);if(fr.length>=W)break;}if(!fr.length)break;}return null;}
function fmt(lv) {
  const parts = [];
  for (const k of ["count", "colors", "taps", "par", "duck", "seed"]) parts.push(k + ": " + JSON.stringify(lv[k]));
  parts.push("objs: " + JSON.stringify(lv.objs));
  if (lv.mix) parts.push("mix: " + JSON.stringify(lv.mix));
  parts.push("bias: " + JSON.stringify(lv.bias));
  if (lv.intro) parts.push('intro: "' + lv.intro + '"');
  parts.push("hint: " + JSON.stringify(lv.hint));
  return "    { " + parts.join(", ") + " },";
}
const out = [];
for (let i = 0; i < LEVELS.length; i++) {
  const lv = LEVELS[i];
  lv.par = beam(lv, 8, lv.taps);
  out.push(fmt(lv));
  process.stderr.write(".");
}
process.stderr.write("\n");
const file = `/* RATTLE — full campaign (T0–T7, ${out.length} levels), generated by
   scripts/dev/gen-campaign.cjs (WR-tuned) + \`par\` (bot-optimal taps) for the
   efficiency-star system. Difficulty tuned to a measured casual-WR curve; \`par\`
   is the expert 3-star target. Regenerate with the script — do not hand-edit. */
(function (root, factory) {
  "use strict";
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.RattleLevels = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const LEVELS = [
${out.join("\n")}
  ];
  return { LEVELS };
});
`;
fs.writeFileSync(path.join(__dirname, "..", "..", "web", "js", "levels.js"), file);
console.error("→ wrote par into web/js/levels.js (" + out.length + " levels)");
